version: '3.9'
services:
  mcm-service:
    image: lacnet/mcm-service:1.0.0
    container_name: ${SPRING_APPLICATION_NAME}
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}
    depends_on:
      - mcm-service-mongo
  mcm-service-mongo:
    image: mongo
    container_name: ${MONGO_HOST}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
  mongo-seed:
    build:
      context: .docker/mongodb
      args:
        - SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}
        - MONGO_USER=${MONGO_INITDB_ROOT_USERNAME}
        - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    depends_on:
      - mcm-service-mongo
  mcm-service-mongo-express:
    image: mongo-express
    ports:
      - '8081:8081'
    environment:
     - ME_CONFIG_MONGODB_SERVER=${MONGO_HOST}
     - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
     - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
     - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
     - ME_CONFIG_MONGODB_AUTH_DATABASE=${MONGO_INITDB_DATABASE}
    depends_on:
      - mcm-service-mongo
    restart: always
  mcm-service-postgres:
    image: postgres:10
    container_name: 'mcm-service-postgres'
    ports:
      - '5432:5432'
  mcm-service-mysql:
    image: mysql
    container_name: mcm-service-mysql
    volumes:
      - ./.docker/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8

#devmongodata:
#    command: echo created
#    image: busybox
#    volumes:
#       - /data/db


#version: "3"
  #services:
    #  java:
      #build:
    #context: ./
      #ports:
    #- "8080:8080"
      #depends_on:
    #- mongo
      #networks:
    #- shared-net
    #restart: always
  #networks:
    #shared-net:
    #driver: bridge