# Mongo docker image
version: '3.9'
services:
  mongo:
    image: mongo
    container_name: mcmMongoDb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - ./.docker/mongodb/data/db/:/data/db/
  mongo-express:
    image: mongo-express
    container_name: mcmMongoExpress
    restart: always
    ports:
      - "8081:8081"
    environment:
     - ME_CONFIG_MONGODB_SERVER=mongo
     - ME_CONFIG_MONGODB_PORT=27017
     - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
     - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
    depends_on:
      - mongo