// Copyright (c) Microsoft Corporation. All rights reserved.

Type.createNamespace('MSCf');MSCf._F$0=function(configurationUrl){this.$0=configurationUrl;}
MSCf._F$0.prototype={$0:null,$1:false,$2:null,$3:null,get_$4:function(){return this.$1;},get_$5:function(){return this.$2;},add_$6:function($p0){this.$7=Delegate.combine(this.$7,$p0);},remove_$6:function($p0){this.$7=Delegate.remove(this.$7,$p0);},$7:null,$8:function(){var $0=new MSCo.HttpRequest(0,this.$0,String.Empty,{},Delegate.create(this,this.$9));$0.execute();},$9:function($p0){if($p0.get_status()===200){try{this.$2=MC.JSON.deserialize($p0.get_responseText());this.$1=true;}catch($0){}}this.$A();},$A:function(){this.$3=document.createElement('iframe');this.$3.style.visibility='hidden';this.$3.attachEvent('onload',Delegate.create(this,this.$B));this.$3.src=this.$2.identity.storageAuthUrl;document.body.appendChild(this.$3);},$B:function(){if(this.$3){var $0=this.$3;this.$3.detachEvent('onload',Delegate.create(this,this.$B));this.$3=null;document.body.removeChild($0);}this.$C();},$C:function(){if(this.$7){this.$7.invoke(this,EventArgs.Empty);}}}
MSCf.ConfigurationService=function(configurationUrl){this.$0=configurationUrl;this.$1=MC.$create_ConfigurationInfo();}
MSCf.ConfigurationService.prototype={$0:null,$1:null,get_current:function(){return this.$1;},add_changed:function(value){this.$2=Delegate.combine(this.$2,value);},remove_changed:function(value){this.$2=Delegate.remove(this.$2,value);},$2:null,loadConfiguration:function(){var $0=new MSCf._F$0(this.$0);$0.add_$6(Delegate.create(this,this.$3));$0.$8();},$3:function($p0,$p1){var $0=$p0;if($0.get_$4()){this.$4($0.get_$5());}},$4:function($p0){this.$1=$p0;if(this.$2){this.$2.invoke(this,EventArgs.Empty);}}}
MSCf._F$0.createClass('MSCf._F$0');MSCf.ConfigurationService.createClass('MSCf.ConfigurationService',null,MC.IConfigurationService);
// ---- Do not remove this footer ----
// Generated using Script# v0.5.1.0 (http://projects.nikhilk.net)
// -----------------------------------
